title: Notebook
description: My notebook. Let check it out!
theme: just-the-docs

url: https://hovanvydut.github.io/hovanvydut

plugins:
  - jekyll-default-layout
  - jekyll-spaceship

enable_copy_code_button: true
color_scheme: light
